### ISSUE TITLE
Receiver SHOULD ACK before dropping datagram frames

### ISSUE THREAD

**Issue by goelvidhi** [tfpauly/draft-pauly-quic-datagram#12]
As QUIC transport provides congestion control, the receiver SHOULD acknowledge all the datagram frames that it received even if it is about to drop it. Some applications might do it implicitly but we want to ensure that all of them comply. Otherwise the congestion control will continue to lower the congestion window without any actual network loss.

This is even more important as the unreliable QUIC doesn't provide flow control.

**Comment by tfpauly** [comment]
I believe this is already covered by the document and does not need text.

The text does say `DATAGRAM frames... are ack-eliciting`. This means that any packet that is received that contains a DATAGRAM frame must be acked. Any implementation that does not do so would not be compliant to the base QUIC transport spec.

**Comment by DavidSchinazi** [comment]
In QUIC we acknowledge packets, not frames. All packets are acknowledged, with the exception that the ack is delayed indefinitely if the packet does not contain any ack-eliciting frames. I don't think we need to add text here.
