### ISSUE TITLE
0-RTT clarifications

### ISSUE THREAD

**Issue by rpaulo** [tfpauly/draft-pauly-quic-datagram#14]
This spec currently is missing details on 0-RTT.  Specifically:

1) Whether the transport parameter needs to be stored for future 0-RTT use. The QUIC Transport spec currently says:

> The definition of new transport parameters (Section 7.3.2) MUST specify whether they MUST, MAY, or MUST NOT be stored for 0-RTT. 

2) How to handle the new TP after 0-RTT.  For example, the TP can be completely gone (and DATAGRAM becomes unsupported) or it could decrease or increase the size of the DATAGRAM.

3) If we tell implementations to store the TP with the 0-RTT metadata, it's possible that we can send DATAGRAM frames in 0-RTT packets but suddenly we won't be able to send any more DATAGRAM frames if the TP is missing after the handshake.  We need language to clarify what to do in this case.

**Comment by tfpauly** [comment]
Good call, we should add the text about how the TP is handled here.
