### ISSUE TITLE
Specify whether empty DATAGRAM frame are allowed

### ISSUE THREAD

**Issue by DavidSchinazi** [tfpauly/draft-pauly-quic-datagram#19]
From @martinthomson ([link to email](https://mailarchive.ietf.org/arch/msg/quic/lSqgErC2E_svoz_28VxohJ39gDg)):

> Is it illegal to send an empty DATAGRAM frame?

**Comment by DavidSchinazi** [comment]
I personally think they should be legal, but either way we should make that explicit in the draft

**Comment by mikkelfj** [comment]
They definitely should be legal. For example, you have a geiger counter and send a list of timestamps in a DATAGRAM. If there where no observed event, you send an empty list. Why would want to special case that? Even if you use flow identifiers, why would the empty, or default, identifier be invalid for e.g. heart beats.

**Comment by Ralith** [comment]
It would be very strange to forbid zero-length datagram frames when zero-length stream frames are permitted.

**Comment by rpaulo** [comment]
@ralith STREAM frames can have zero length because they can carry the FIN bit only.

**Comment by Ralith** [comment]
Aren't they permitted in all cases as of https://github.com/quicwg/base-drafts/pull/1350?

**Comment by rpaulo** [comment]
@Ralith Yes, I was just trying to make a point about the lack of FIN in DATAGRAM.  I'm not against having a zero length DATAGRAM frame.

**Comment by nibanks** [comment]
I also think zero length should be allowed. Zero length UDP datagrams are allowed. What if a protocol that uses zero length UDP datagrams wants to be ported to QUIC and use QUIC datagrams?

**Comment by tfpauly** [comment]
Agreed with @nibanks that zero-length datagram frames should be supported, in the same way that UDP allows it.
