### ISSUE TITLE
Explain how max datagram frame size interacts with PTMU

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/draft-pauly-quic-datagram#2]
We should add text to explain how the application may effectively still have smaller datagram payload sizes due to small PMTU (and interface MTU) even if the max datagram frame size is large. Essentially, the effective at any point is the MIN(max frame size, PMTU, MTU)

**Comment by DavidSchinazi** [comment]
Agreed. Note that PMTU <= MTU because PMTU is defined as min (MTU_l) for all links l

**Comment by tfpauly** [comment]
Fair point!

**Comment by erickinnear** [comment]
Also discussed interaction with PMTUD in Prague: Noted that some of that interaction with QUIC will need to be solved more generally, but this issue is more specific and covers specific text.
