### ISSUE TITLE
Should we call DATAGRAM ID -> DATAGRAM FLOW ID?

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/draft-pauly-quic-datagram#3]
Should we call DATAGRAM ID -> DATAGRAM FLOW ID?
This may be a bit clearer

**Comment by DavidSchinazi** [comment]
Some applications might want to use the ID to identify flows, but some could use it to just identify the datagrams. I agree that we could clarify the name but flow might be restrictive.

**Comment by erickinnear** [comment]
I thought we explicitly referred to "application level flow" in the document -- do we want to allow going beyond that concept?

**Comment by DavidSchinazi** [comment]
Fair enough, flows can be of length 1 so I guess renaming to DATAGRAM FLOW ID sounds fine.

**Comment by erickinnear** [comment]
Parking this until it's decided whether or not this ID should be included at all.
Tracked by issue #8.

**Comment by tfpauly** [comment]
For now called it Flow ID in #9, but can change again or be removed in the future.
