### ISSUE TITLE
Consider retransmission bit leakage

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/draft-pauly-quic-datagram#32]
Rephrasing what I mentioned at the mic, imagine a scenario where an application uses DATAGRAM to send a single fixed message ("fire the missile"). An adversary on path *can* start selectively dropping packets and checking to see whether or not they're retransmitted to learn whether or not this special message was sent. (Retransmission detection could be done by looking at the size of the QUIC packet carrying the DATAGRAM, for example.) 

I don't claim this is easy to do in practice, or useful, but I think it does raise interesting questions about how this new frame affects QUIC's security posture. Perhaps some text in the security considerations is needed?

**Comment by mikkelfj** [comment]
How would that be different from streams in ordinary QUIC? Here you can also drop packets and look for retransmissions of a specific size? If there is overlap, this issue belongs to QUIC transport security considerations in general.

**Comment by DavidSchinazi** [comment]
Closing this issue, follow along on the [new repository](https://github.com/quicwg/datagram/issues/2).
