### ISSUE TITLE
Should DATAGRAM frames include some sort of ID field

### ISSUE THREAD

**Issue by erickinnear** [tfpauly/draft-pauly-quic-datagram#8]
At the side meeting in Prague, we had lots of discussion about whether or not DATAGRAM frames should include the ID field. Creating this issue to track resolving that discussion.

**Comment by erickinnear** [comment]
@ianswett Made a very interesting comment about the transport not including values that are not used by the transport in some way.

**Comment by DavidSchinazi** [comment]
There was also a good point made that the datagram identifier is analogous to port numbers in UDP - the transport does not use them either but they allow for demultiplexing higher layers.

**Comment by rpaulo** [comment]
I *strongly* oppose removing an ID from the DATAGRAM frame.  I thought we had reached a compromise by having an optional ID.

**Comment by ianswett** [comment]
Can you explain the benefit of including an ID at the transport layer instead of the application layer?  I don't believe it saves bytes and the transport does nothing with it.

**Comment by rpaulo** [comment]
@ianswett The benefit is multiplexing at the transport layer, which is what I would like to achieve. I don't want to do multiplexing at the application.

**Comment by ianswett** [comment]
To clarify, are you thinking multiple applications running on a single QUIC connection at once?  If so, I think that's a wider problem than DATAGRAM.  For example, there is no way for anything besides HTTP requests to use bidirectional streams in HTTP/3.

**Comment by rpaulo** [comment]
@ianswett it may be a wider problem but I don't see the reason why we have to limit what the DATAGRAM extension can provide.

**Comment by tfpauly** [comment]
We had a productive lunch meeting for Datagram today after the QUIC session (with Lars, ekr, Martin Thomson, Lucas Pardue, David Schinazi, Eric Kinnear, Nick Banks, and Tommy Pauly in attendance).

The group agreed that the relevant open issue was the use of flow IDs in the transport. The decision we came to collectively was to:

- Remove Flow Identifiers from the QUIC DATAGRAM (transport) draft. Specify that each application is responsible for defining its datagram flow management scheme.
- David will be creating a new document to define how HTTP/3 marks and uses DATAGRAM frames.

We can add more details if people have questions.
